# 데이터 확인

In [1]:
import pandas as pd

In [2]:
# 파일 읽기
month_2017 = pd.read_excel('../데이터 수집/data/2017_month.xlsx')
month_2018 = pd.read_excel('../데이터 수집/data/2018_month.xlsx')
month_2019 = pd.read_excel('../데이터 수집/data/2019_month.xlsx')
month_2020 = pd.read_excel('../데이터 수집/data/2020_month.xlsx')
month_2021 = pd.read_excel('../데이터 수집/data/2021_month.xlsx')

In [3]:
month_2017.head()

     년도  월  순위               타이틀           가수           장르
0  2017  1   1      첫눈처럼 너에게 가겠다  에일리 (AILEE)    OST / 드라마
1  2017  1   2         Beautiful        Crush    OST / 드라마
2  2017  1   3  당신의 밤 (Feat. 오혁)     황광희 & 개코    가요 / 랩/힙합
3  2017  1   4            좋다고 말해       볼빨간사춘기      가요 / 인디
4  2017  1   5         오랜 날 오랜 밤    AKMU (악뮤)  가요 / 블루스/포크

In [4]:
month_2018.head()

     년도  월  순위                        타이틀                가수           장르
0  2018  1   1                       그날처럼               장덕철     가요 / 발라드
1  2018  1   2                  instagram              DEAN  가요 / R&B/소울
2  2018  1   3                        비행운     문문 (MoonMoon)      가요 / 인디
3  2018  1   4                         선물  멜로망스 (MeloMance)      가요 / 인디
4  2018  1   5  Havana (Feat. Young Thug)    Camila Cabello      POP / 팝

In [5]:
month_2019.head()

     년도  월  순위              타이틀                   가수           장르
0  2019  1   1             넘쳐흘러  엠씨더맥스 (M.C the MAX)     가요 / 발라드
1  2019  1   2           벌써 12시                   청하      가요 / 댄스
2  2019  1   3             180도                    벤     가요 / 발라드
3  2019  1   4             SOLO          제니 (JENNIE)    가요 / 랩/힙합
4  2019  1   5  습관 (Bad Habits)            숀 (SHAUN)  가요 / 일렉트로니카

In [6]:
month_2020.head()

     년도  월  순위                타이틀                 가수         장르
0  2020  1   1             METEOR       창모 (CHANGMO)  가요 / 랩/힙합
1  2020  1   2               아무노래          지코 (ZICO)  가요 / 랩/힙합
2  2020  1   3             Psycho  Red Velvet (레드벨벳)    가요 / 댄스
3  2020  1   4           Blueming           아이유 (IU)     가요 / 락
4  2020  1   5  늦은 밤 너의 집 앞 골목길에서                 노을   가요 / 발라드

In [7]:
month_2021.head()

,년도,월,순위,타이틀,가수,장르
0,2021,1,1,우린 어쩌다 헤어진 걸까,허각,가요 / 발라드
1,2021,1,2,VVS (Feat. JUSTHIS) (Prod. by GroovyRoom),미란이 (Mirani) & 먼치맨 (MUNCHMAN) & Khundi Panda &...,가요 / 랩/힙합
2,2021,1,3,Dynamite,방탄소년단,가요 / 댄스
3,2021,1,4,밤하늘의 별을 (2020),경서,가요 / 인디
4,2021,1,5,요즘,양다일,가요 / 발라드

# 데이터 전처리

In [ ]:
# 장르 수정
for data in [month_2017, month_2018, month_2019, month_2020, month_2021]:
    for i in range(len(data)):
        # 'OST/드라마', 'OST/해외영화' -> OST로 통일
        if (data['장르'][i].startswith('OST')) or (data['장르'][i].startswith(' 드라마')) or (data['장르'][i].startswith(' 해외영화')):
            data['장르'][i] = 'OST'
            
        # '가요/..', 'POP/..' 등 뒤에 써진 세부 장르로 변경
        else:
            data['장르'][i] = data['장르'][i].split()[-1]

In [ ]:
# '전체'로 표시된 장르 멜론에서 찾아서 변경
month_2017['장르'][193] = 'R&B/소울'
month_2017['장르'][622] = '댄스'
month_2017['장르'][720] = '댄스'
month_2017['장르'][845] = '댄스'
month_2017['장르'][978] = '댄스'
month_2017['장르'][1074] = '댄스'
month_2017['장르'][1181] = '댄스'
month_2017['장르'][912] = '발라드'
month_2017['장르'][1034] = '발라드'
month_2017['장르'][1173] = '발라드'

month_2018['장르'][55] = '댄스'
month_2018['장르'][183] = '댄스'
month_2018['장르'][398] = '인디'
month_2018['장르'][494] = '랩/힙합'
month_2018['장르'][594] = '랩/힙합'
month_2018['장르'][1182] = '댄스'

month_2019['장르'][1023] = '댄스'
month_2019['장르'][1081] = '댄스'
month_2019['장르'][1105] = 'R&B/소울'
month_2019['장르'][1139] = 'R&B/소울'
month_2019['장르'][1155] = '댄스'
month_2019['장르'][1167] = '댄스'
month_2019['장르'][1168] = 'R&B/소울'

month_2020['장르'][9] = 'R&B/소울'
month_2020['장르'][68] = '댄스'
month_2020['장르'][117] = 'R&B/소울'
month_2020['장르'][190] = '댄스'
month_2020['장르'][232] = 'R&B/소울'
month_2020['장르'][342] = 'R&B/소울'
month_2020['장르'][464] = 'R&B/소울'
month_2020['장르'][578] = 'R&B/소울'
month_2020['장르'][687] = 'R&B/소울'
month_2020['장르'][789] = 'R&B/소울'
month_2020['장르'][886] = 'R&B/소울'
month_2020['장르'][1129] = '댄스'

month_2021['장르'][403] = '댄스'
month_2021['장르'][503] = '댄스'
month_2021['장르'][615] = '댄스'
month_2021['장르'][720] = '댄스'

In [11]:
# 파일 저장
month_2017.to_excel('./data/2017_month.xlsx', index=False)
month_2018.to_excel('./data/2018_month.xlsx', index=False)
month_2019.to_excel('./data/2019_month.xlsx', index=False)
month_2020.to_excel('./data/2020_month.xlsx', index=False)
month_2021.to_excel('./data/2021_month.xlsx', index=False)